[tool.poetry]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["infinity-studio"]"]

[tool.poetry.dependencies]
python = ">=3.10.0,<3.11"
qiskit = "^0.45.0"
matplotlib = "^3.8.2"
nvdlib = "^0.7.6"
pandas = "^2.1.3"
scikit-learn = "^1.3.2"
pyjokes = "^0.6.0"
pywhatkit = "^5.4"
speechrecognition = "^3.10.0"
wikipedia = "^1.4.0"
pyttsx3 = "^2.90"
pyautogui = "^0.9.54"
numpy = "^1.26.2"
cirq = "^1.3.0"

[tool.pyright]
# https://github.com/microsoft/pyright/blob/main/docs/configuration.md
useLibraryCodeForTypes = true
exclude = [".cache"]

[tool.ruff]
# https://beta.ruff.rs/docs/configuration/
select = ['E', 'W', 'F', 'I', 'B', 'C4', 'ARG', 'SIM']
ignore = ['W291', 'W292', 'W293']

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"